### ISSUE TITLE
Terrain Shader Error

### ISSUE THREAD

**Issue by MoAkra** [Dustyroom/flat-kit-doc#6] opened 2020-12-21 23:34 UTC
Hi, 

I get this error when I apply the Flat Kit Terrain shader to a material, or use the FlatTerrain-TerrainShader that comes with the package.

Interestingly, when I open the demo scene (Valley - Scene - With Fog), the terrain shader seems fine. I'm using Map Magic, Vegetation Studio Pro and The Vegetation Engine in my project, so maybe they're causing the problem. 

Thanks for the support!

Mo

### URP 8.2.0

![image](https://user-images.githubusercontent.com/56600104/102830961-82bc9900-43e2-11eb-8531-41ac4f0b3ffc.png)
![image](https://user-images.githubusercontent.com/56600104/102831408-a6ccaa00-43e3-11eb-8d01-e9eb2ce2c0ef.png)
![image](https://user-images.githubusercontent.com/56600104/102831302-581f1000-43e3-11eb-8892-30678ee7cf4c.png)

**Comment by dustyroom-studio** [comment] 2020-12-22 05:46
Hi Mo,

Since it works well in the Valley demo scene, could it be something with your scene? To probably pinpoint the issue, I'd suggest to try temporarily stripping down the problematic scene component-by-component while constantly checking whether the issue is gone. Start with the assets you mentioned, until you get the terrain itself. If the issue persists, then it would be helpful to start comparing all the aspects of the terrains from your scene and the Valley scene.
If after that the error is still there, I'd like to ask you to make a step-by-step guide to reproduce the issue using the simplest possible scene when the issue starts to occur.

Please, let us know how it is going so that we could spot the cause for the error.

**Comment by TyroByte968** [comment] 2020-12-27 18:03
uncheck the draw instanced option in the terrain settings tab on your terrain

**Comment by dustyroom-studio** [comment] 2021-01-19 18:51
@MoAkra please let us know if the issue is still happening.
Closing the issue for now.

**Closed by dustyroom-studio** 2021-01-19 18:51 UTC

**Comment by TyroByte968** [comment] 2021-01-19 19:28
Oh my bad, I believe this issue has been fixed. I thought I closed the
thread. Solution was to uncheck draw instanced option on terrain settings
as commented below. Issue will still happen in 2019.4 LTS if you check the
option.
