### ISSUE TITLE
No URP Package via PackageManager

### ISSUE THREAD

**Issue by vailKAKO** [Dustyroom/flat-kit-doc#26] opened 2021-03-15 02:24 UTC
**Describe the bug**
There is no URP Package via PackageManager, only Builtin.
Builtin is installed at the time of import.
If you import from Package Manager as described in the document,
Go to Assets (in Project tab) ▶︎ “URP Package” folder ▶︎ FlatKit URP ▶︎ unpack.
does not exist.

**To Reproduce**
Importing FlatKit latest 2.1.4 via PackageManager in URP project on Unity 2019.4.20. (The same problem has been confirmed in other URP projects as well.)

**Expected behavior**
Package exists as described in the document.

**Unity details:**
 - Flat Kit version: [e.g. 2.1.4]
 - Unity version: [e.g. 2019.4.20]
 - Graphics Pipeline: [URP]
 - Development OS: [macOS BigSur]

**Comment by dustyroom-studio** [comment] 2021-03-15 06:27
Hi,

Thank you for reporting this.
If I understood correctly, you took [this guide](https://flatkit.dustyroom.com/#82-urp-installation) instead of [this one](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)
If so, please, follow the latter one.

Once you complete all 6 steps in the guide from the second link ([this one](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)), Flat Kit should be ready to go. If the issue is still there, could you please do the following:

- Could you please send me a screenshot of the Package Manager during the import, like here:
![fk-import-1](https://user-images.githubusercontent.com/74666746/111111301-c4368d80-8566-11eb-9364-e32df119a418.png)

- Also, please, send me a screenshot of Flat Kit folder's contents in Project tab in Unity.
![fk-import-2](https://user-images.githubusercontent.com/74666746/111111362-d9132100-8566-11eb-972c-a3441b5f884e.png)

- Have you unpacked the [Render Pipeline] URP unitypacke? It looks like here:
![fk-import-3](https://user-images.githubusercontent.com/74666746/111111555-3a3af480-8567-11eb-8608-3dd705be180c.png)

Hope it helps

**Comment by vailKAKO** [comment] 2021-03-15 06:53
Thank you so much for your reply!
I was referring to the former, as you said.

I thought it might be a problem in my environment, so I tried it right after creating a new project.
Since the icons are different, I deleted the UnityPackage stored in Unity and tried again, but the situation is the same.
The following is a part of the progress of the specified part. Because of this condition, the image in this picture is imported even if Import is done, and UnityShaderCompiler runs out of control when Importing for some reason, the image after Importing is omitted.

(1) Downloaded state as before.
![first_download](https://user-images.githubusercontent.com/47889121/111114347-78a3d400-85a6-11eb-9734-678aac82a0ed.png)

(2) The old version is also displayed for some reason, and it does not change no matter how many times I try to update.
![second_anotherversionappear](https://user-images.githubusercontent.com/47889121/111114382-7fcae200-85a6-11eb-8d73-e08679b84f51.png)

(3) Pressing "Import" in that state.
![third_importphase](https://user-images.githubusercontent.com/47889121/111114400-85c0c300-85a6-11eb-87b1-606ad60a9619.png)

(4) Deleting the UnityPackage stored inside Unity, and pressing Download and Import.
![fourth_re_downloadandimport](https://user-images.githubusercontent.com/47889121/111114417-8c4f3a80-85a6-11eb-8167-00be452e9d39.png)


These are all the states right after I created the project with URP on 2019.4.20.

**Comment by dustyroom-studio** [comment] 2021-03-15 07:33
Thank you for your screenshots and all the additional info.
It seems like it should be working ok but your second screenshot shows the 'white' icon of Flat Kit. It is the icon for pre-2 version of Flat Kit. In v.2 and later the icon became 'purple'. This leads me to the following possible reason: since you've got an older version of Flat Kit — you'll need to select the newer one and press Update. But, as you were saying, you couldn't update because it wouldn't let you do that, I think it is a cache problem. Could you please clear the Package Manager cache and re-import Flat Kit? Here's how to do it in macOS:

- Delete Flat Kit from your project if you haven't yet
- Press Cmd + Shift + G in any Finder window or find 'Go' menu on the top bar and press 'Go to Folder'
- Type/paste this path in the window that pops out:
~/Library/Unity/Asset Store-5.x
- Delete the cache in that folder
- Relaunch Unity
- Go to Window -> Package Manager -> My Assets -> Flat Kit
- Update Flat Kit to the newest version
- Install Flat Kit as described in the [guide](https://flatkit.dustyroom.com/#2-quick-start-beginning-to-work-with-flat-kit)

Let me know how it goes.

**Comment by vailKAKO** [comment] 2021-03-15 08:30
Thank you very much.
I've taken the following actions, and I'm in the state shown in the attached screenshot.

1) Delete all files in AsssetStore-5.x as you told me.
2) Delete Chache in the directory above.
(3) Delete the Image Cashe in AssetStore.
URP, 2019.4.20
URP,2019.4.20 The result is as shown in the attached screenshot, although the download also started from scratch.
I will try deleting the cache when I have time.

As an additional report, the date I purchased this asset is
Dec 29, 2020
I'm not sure why the 1.5.5 version is appearing this time.
Dec 18, 2019
I'm at a loss as to why the 1.5.5 version ...... is from a time when I didn't own it yet.

I'm going to try everything I can think of to figure out what's going on, but I'll let you know as soon as I can.

![SS_actiongoes](https://user-images.githubusercontent.com/47889121/111124443-de4a8d00-85b3-11eb-8cc0-f25d24dc263e.png)

**Comment by dustyroom-studio** [comment] 2021-03-15 08:59
Yes, it definitely looks like the cache problem. In the more recent 2020's Unity versions it is a more rare issue. You see older versions because, theoretically, apart from the latest version, you should also have access to any previous version of Flat Kit. But the bug is that you can't have the latest one... It is the Unity's bug of a Package Manager and the only workaround would be trying deleting the cache and trying importing the asset (not only Flat Kit) from a more recent version of Unity.
I am sorry for this issue, many developers requested Unity to fix this weird problem...

So, I'd suggest you doing this:
- Try cleaning the cache, installing Unity 2020.2.x or 2020.3.x, importing Flat Kit using that version of Unity, moving it to your existing project in 2019.4.20f1
- Shoot me an email and I'll directly send you the correct package.

**Comment by dustyroom-studio** [comment] 2021-03-26 19:45
Please re-open the issue if it's not been resolved.

**Closed by dustyroom-studio** 2021-03-26 19:45 UTC
