### ISSUE TITLE
Fog Feature prevents rendering of transparent materials

### ISSUE THREAD

**Issue by niccabc** [Dustyroom/flat-kit-doc#40] opened 2021-04-24 05:49 UTC
**Describe the bug**
The Flatkit fog renderer feature appears to be incompatible with transparent materials.
Specifically I am referring to materials with Surface Type set to Transparent.
This prevents me from using the particle effects in my project that have transparency :(

**To Reproduce**
1. Create a new material and set Surface Type (Under Surface Options) to Transparent.
2. Create a 3D Gameobject and apply the transparent material to it.
3. Select the Flatkit Example Forward Renderer in the Project Window.
4. In the Inspector Window, enable Flat Kit Fog under Renderer Features.
5. As soon as the fog is enabled, the object with the transparent material will stop rendering.
6. Disable the Fog, and the object reappears.
7. This occurs with both default unity shaders and with the Flatkit Stylized Surface shader.
8. This occurs regardless of object distance from camera.
9. This occurs regardless of Fog Settings.

**Expected behavior**
I expect the fog feature to not prevent certain objects/materials from rendering! :)

**Unity details:**
 - Flat Kit version: 2.1.8
 - Unity version: 2020.3.5f1
 - Graphics Pipeline:  URP
 - URP version (if applicable): 10.4.0
 - Development OS: Mac OS

**Build platform:**
 - Platform:  Mac OS
 - Test device: Mac Pro

**Comment by dustyroom-studio** [comment] 2021-04-24 06:53
Thanks for reporting this.

The fog image effect currently doesn't work with the transparent objects because they are not reflected in Unity's depth image. To overcome this limitation we would need to introduce a custom renderer feature that renders depth for the transparent objects.

That change is in our plans, but I can't give a time estimate for the solution at this point. Please let us know if this feature is critical for your project.

**Comment by niccabc** [comment] 2021-04-24 17:51
Thanks for the quick response!

That all makes sense, and I'm glad to hear that you are working on a fix. Solving this issue is definitely critical for my project. For the time being, I will have to find a work around :(

Also, while we're on the subject of the fog,I've noticed another issue.
When I move the outline effect above the fog in the renderer features list, the outlines no longer render.
It would be so, so great if the fog could influence the outline colors.

**Comment by dustyroom-studio** [comment] 2021-04-24 18:02
Thank you for your patience!
Regarding the fog affecting the outlines, please, have a look at the order of the Renderer Features in the Forward Renderer. This order of the effects works top to bottom, meaning the effect lower in the chain has an influence on those above it. We have a note about it in our manual (see the screenshot) — [here](https://flatkit.dustyroom.com/#83-flat-kit-image-effects-in-urp)
Hope this will help.

**Comment by niccabc** [comment] 2021-04-24 18:35
Yes, that is the effect I'm after. However, It is not working properly for me. :(
Here I have outlines underneath fog and they render:
![Screen Shot 2021-04-24 at 11 30 30 AM](https://user-images.githubusercontent.com/83108399/115969230-d524d800-a4f0-11eb-8d65-e88dfeb8ebc7.png)

But here, with fog underneath outlines, the outlines do not render at all:
![Screen Shot 2021-04-24 at 11 30 52 AM](https://user-images.githubusercontent.com/83108399/115969264-feddff00-a4f0-11eb-91cb-eb366fae0059.png)

**Comment by dustyroom-studio** [comment] 2021-04-24 18:52
Could you please go to outlines settings and try adjusting Render Event parameter. 'After Rendering Transparents' or any similar event. Make sure you have the correct settings file selected in Edit - Project Settings - Graphics and Quality panels (both panels). Please, let me know if it won't work for you. 
Render Event parameter is [described here](https://flatkit.dustyroom.com/#42-outline-image-effect).

**Comment by niccabc** [comment] 2021-04-24 18:58
AH yes! Changing the Render Event parameter did the trick. Thanks for your help! :)

**Comment by albrrt** [comment] 2021-05-16 11:17
I’m adding my voice here for transparent materials.

This problem also affects World-Space UI (we’re using TextMeshPro) so it’s quite critical for VR use cases.

Is there a timeline for this fix? 

Thank you

**Comment by dustyroom-studio** [comment] 2021-05-16 17:01
> I’m adding my voice here for transparent materials.
> 
> This problem also affects World-Space UI (we’re using TextMeshPro) so it’s quite critical for our use-case
> 
> Is there a timeline for this fix?
> 
> Thank you

Hi, @albrrt 

Could you please specify what exactly doesn't work for you. Also, if you can, please add your set-up details such as Unity, URP, Flat Kit versions and build targets.

Thank you.

**Comment by beareality** [comment] 2021-05-17 17:51
Hi @dustyroom-studio, I also need to get the fog image effect working on transparent objects.

**Comment by dustyroom-studio** [comment] 2021-05-17 18:32
> Hi @dustyroom-studio, I also need to get the fog renderer feature working on transparent objects.

Hi @beareality 

Could you please let me know your setup details, like Unity, Universal RP and Flat Kit versions. You can find those if you go to Project panel -> Assets -> Flat Kit -> Readme. Ince you select the Readme file, you should be able to see all the versions numbers at once. A screenshot of this panel would help.

Also, please add as many details which may help as possible. You can consider writing to info@dustyroom.com as well.

Thank you.

**Comment by beareality** [comment] 2021-05-18 09:58
Flat Kit: 2.2.0, URP: 10.5.0, Unity: 2020.3.8f1
![2021-05-18 11_58_15-Window](https://user-images.githubusercontent.com/35265481/118632112-6590c880-b7d0-11eb-84a7-cb79f3eeaa8e.png)

**Comment by albrrt** [comment] 2021-05-18 21:53
@dustyroom-studio here is my config
![FlatKit Version](https://user-images.githubusercontent.com/28485330/118727880-699e0400-b82b-11eb-9441-aca434b0b400.JPG)


and here are the steps to reproduce my issue:

1) Create a new Unity project with URP template
2) Import TextMeshPro Essential Resources
![Import_TMP_Essentials](https://user-images.githubusercontent.com/28485330/118728269-cb5e6e00-b82b-11eb-9727-5f789b440e3d.jpg)


3) Import FlatKit 2.2.0
4) Import FlatKit URP Package
5) Open the Valley demo scene with Fog
6) Create a new canvas with Text (TMP)
![hierarchy](https://user-images.githubusercontent.com/28485330/118728177-a5d16480-b82b-11eb-8c10-3d9fa5f9212b.JPG)

7) Set your canvas to World Space and move it in front of Camera 1. Set the event camera to Camera 1.
The camera doesn't render the canvas.
![Canvas_World_Space_Fog_On](https://user-images.githubusercontent.com/28485330/118727312-7a01af00-b82a-11eb-9b9a-18614d3e9818.JPG)

8) Disable the fog in the Renderer 
The camera renders the canvas
![Canvas_World_Space_Fog_Off_2](https://user-images.githubusercontent.com/28485330/118727781-3ce9ec80-b82b-11eb-8f98-c85061619612.JPG)

**Comment by dustyroom-studio** [comment] 2021-06-18 16:59
Thank you for the screenshots @albrrt, we are able to reproduce this issue. It's going to be fixed in the next update to Flat Kit, which should appear on the Asset Store early next week.

**Comment by albrrt** [comment] 2021-06-24 16:44
Thanks @dustyroom-studio the canvas components seem to render correctly in v.2.2.6 using FlatKit Fog. 

I still need to test URP/Lit materials with Transparent surface types (@niccabc 's original problem) and get back to you

**Closed** 2022-04-11 20:16 UTC
Labels: bug
